name: Issue label removing and adding

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "imkevinisme/version-action"

      # - name: Removing and adding label = "Deployed with version"
      #   if: github.event.label.name == 'Ready to deploy'
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.removeLabel({
      #         name: "Ready to deloy"
      #       })

      - name: Adding label
        run: |
          echo ${{github.repository}}
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: 1
          LABELS: Deployed
