name: Issue label removing and adding

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env: ${{github.repository}} = 'imkevinisme/version-action'

    steps:
      - name: Find all issue with "Ready to deploy" label
        uses: lee-dohm/select-matching-issues@v1
        with:
          query: "label:"
          token: ${{github.token}}
      - name: Listing out all the repo issue
        run: cat ${{github.repository}}

      #       })
      # - name: Removing and adding label = "Deployed with version"
      #   if: github.event.label.name == 'Ready to deploy'
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.removeLabel({
      #         name: "Ready to deloy"
