name: Issue label removing and adding

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Find all issue with "Ready to deploy" label
        id: deploy
        uses: lee-dohm/select-matching-issues@v1
        with:
          path: imkevinisme/version-action
          format: list
          query: label:documentation
          token: ${{github.token}}

      - name: Close found issues
        run: cat ${{ steps.deploy.outputs.path }}

      #       })
      # - name: Removing and adding label = "Deployed with version"
      #   if: github.event.label.name == 'Ready to deploy'
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.removeLabel({
      #         name: "Ready to deloy"
